In [4]:
import numpy as np

In [5]:
lista =[1,2,3,4,5,6,7,8,9]

In [6]:
arr=np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
matriz=[[1,2,3],[4,5,6],[7,8,9]]
matriz=np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[1]+arr[5]

8

In [10]:
matriz[0,2]

3

In [11]:
arr[1::2]

array([2, 4, 6, 8])

In [12]:
arr[-3:]

array([7, 8, 9])

In [13]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

# ***Segunda Clase Tipos de datos***


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr.dtype

dtype('int64')

In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9],dtype='float64')
arr.dtype
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr=arr.astype(np.float64)
arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr=arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [18]:
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr=arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'],
      dtype='|S21')

In [19]:
arr=np.array(['0','1','2','3','4','5','6','7','8','9'])
arr=arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

# ***Dimensiones***

In [20]:
scalar=np.array(42)
print(scalar)
scalar.ndim

42


0

In [21]:
matriz=np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [22]:
tensor=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

# ***Agregar o quitar Dimensiones***

In [23]:
vector=np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [24]:
expand=np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [25]:
print(vector,vector.ndim)
vector_2=np.squeeze(vector) #lleva a una dimension util
print(vector_2,vector.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 10


# ***Arrays***

In [26]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
np.linspace(0,10,100) #inicio fin hasta donde quiero que llegue

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [33]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.random.rand()

0.4420334907310054

In [37]:
np.random.rand(4)

array([0.42976962, 0.43482559, 0.94314125, 0.85124135])

In [38]:
np.random.rand(4,4)

array([[0.95263923, 0.07682165, 0.18786813, 0.98737484],
       [0.38465925, 0.2949988 , 0.9867514 , 0.71514722],
       [0.99610974, 0.06390568, 0.5033231 , 0.81671501],
       [0.12149577, 0.2175998 , 0.17753789, 0.89831429]])

In [39]:
np.random.randint(1,15)

3

In [40]:
np.random.randint(1,100,(10,10))

array([[26, 55,  6,  8, 65, 27, 90, 77, 46, 16],
       [73, 23, 94, 22, 81,  9, 82, 88, 26, 86],
       [30, 32, 82, 27, 96, 83, 30, 11, 31,  3],
       [71, 30, 52, 40, 62, 68, 81, 77, 10, 52],
       [87, 74, 10, 24, 94, 10, 30, 84, 79, 77],
       [58, 21, 99, 49, 60, 56, 21,  2, 54,  9],
       [38, 88, 52, 16, 87, 41, 49, 79, 44, 55],
       [66, 76, 23, 28, 37, 74, 88,  6, 73, 98],
       [67, 84, 78, 10, 35, 57, 56, 59, 26, 47],
       [47, 88,  1, 11, 36, 80, 25, 45, 33, 43]])

# ***Shape y Reshape***

In [50]:
array=np.random.randint(1,10,(3,2))
print(array)

array.shape

[[7 9]
 [2 9]
 [9 5]]


(3, 2)

In [51]:
array.reshape(1,6)

array([[7, 9, 2, 9, 9, 5]])

In [52]:
array.reshape(2,3)

array([[7, 9, 2],
       [9, 9, 5]])

In [53]:
np.reshape(array,(1,6))

array([[7, 9, 2, 9, 9, 5]])

In [54]:
np.reshape(array,(2,3),'C')

array([[7, 9, 2],
       [9, 9, 5]])

In [55]:
np.reshape(array,(2,3),'F')

array([[7, 9, 9],
       [2, 9, 5]])

In [56]:
np.reshape(array,(2,3),'A')

array([[7, 9, 2],
       [9, 9, 5]])

# ***Funciones principales***

In [58]:
arr=np.random.randint(1,20,10)
print(arr)

[ 1  4  3 15  6  9  8  3  4 17]


In [60]:
matriz=arr.reshape(2,5)
print(matriz)

[[ 1  4  3 15  6]
 [ 9  8  3  4 17]]


In [64]:
arr.max()

17

In [65]:
matriz.max(0) #por columna

array([ 9,  8,  3, 15, 17])

In [66]:
matriz.max(1) #por fila

array([15, 17])

In [67]:
arr.argmax() #el indice del maximo

9

In [71]:

print(matriz.argmax(0))
matriz.argmax(1)


[1 1 0 0 1]


array([3, 4])

In [72]:
matriz.min(0)

array([1, 4, 3, 4, 6])

In [73]:
matriz.argmin(0)

array([0, 0, 0, 1, 0])

In [75]:
print(arr)
arr.ptp() #peak to peak la diferencia de pico a pico

[ 1  4  3 15  6  9  8  3  4 17]


16

In [77]:
print(matriz)
matriz.ptp(0)

[[ 1  4  3 15  6]
 [ 9  8  3  4 17]]


array([ 8,  4,  0, 11, 11])

In [88]:
print(matriz)
matriz.ptp(1)


[[ 1  3  3  4  4]
 [ 6  8  9 15 17]]


array([ 3, 11])

In [81]:
print(arr)
np.percentile(arr,50)

[ 1  4  3 15  6  9  8  3  4 17]


5.0

In [90]:
arr=np.random.randint(1,20,10)
print(arr)
arr.sort() #ordena de menor a mayor pero afexta el arreglo original
print(np.sort(arr))
print(arr)


[12 19 15 17  8  7  4  1  5 10]
[ 1  4  5  7  8 10 12 15 17 19]
[12 19 15 17  8  7  4  1  5 10]


In [92]:
np.median(arr)

9.0

In [93]:
np.median(matriz,0)

array([ 3.5,  5.5,  6. ,  9.5, 10.5])

In [94]:
np.std(arr)#desviación estandar

5.6000000000000005

In [95]:
np.var(arr) #varianza

31.360000000000003

In [96]:
np.mean(arr) #media

9.8

In [124]:
a= np.array([[1,2],[3,4]])
b= np.array([5,6])
print(b)
a

[5 6]


array([[1, 2],
       [3, 4]])

In [125]:
print(a.ndim)
print(b.ndim)
b=np.expand_dims(b,axis=0)
print(b)
np.concatenate((a,b),axis=0)#tienen que ser de las mismas simenciones

2
1
[[5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [126]:
print(a.ndim)
print(b.ndim)
print(b)
np.concatenate((a,b),axis=1)


2
2
[[5 6]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [127]:

np.concatenate((a,b.T),axis=1) #b.T es la transpuesta de B

array([[1, 2, 5],
       [3, 4, 6]])

# ***Copy***

In [131]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
trozo_de_arr=arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [135]:
trozo_de_arr[:]=0
print(trozo_de_arr)
print(arr) #se afecta el objeto padre

[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]


In [136]:
arr_copy=arr.copy() #se respeta el valor de lalista original
arr_copy


In [138]:
arr_copy[:]=100
print(arr_copy)
print(arr) #prueba

[100 100 100 100 100 100 100 100 100 100 100]
[ 0  0  0  0  0  0  6  7  8  9 10]


# ***Condiciones***

In [143]:
arr=np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [145]:
indices_cond=arr>5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [149]:
arr[indices_cond] #filtra los que estan en true
arr[arr>5] #filtra los que estan en true

array([ 6,  7,  8,  9, 10], dtype=int8)

In [151]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [152]:
arr[arr>5]=99
arr #modifico el array

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

# ***Operaciones***

In [153]:
lista=[1,2]
lista

[1, 2]

In [155]:
lista*2 #duplica los datso

[1, 2, 1, 2]

In [156]:
arr=np.arange(0,10)
arr2=arr.copy()

In [157]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [158]:
arr*2 #si se aplica la multiplicación

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [159]:
arr+2 #si se aplica la operación

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [160]:
arr2**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [161]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [166]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [167]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [168]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [169]:
np.matmul(matriz,matriz2.T) #producto punto

array([[ 30,  80],
       [ 80, 255]])

In [171]:
matriz @ matriz2.T #producto punto

array([[ 30,  80],
       [ 80, 255]])